//! Poseidon hash wrapper (BN254 scalar field) for the airdrop/eligibility
//! Merkle tree, backed by `light-poseidon`'s pre-generated `bn254_x5`
//! parameters.
//!
//! Why this crate: hand-rolling Poseidon round constants / MDS matrices is a
//! common source of subtle, hard-to-detect vulnerabilities (e.g. weak round
//! constants enabling algebraic attacks). `light-poseidon` ships parameters
//! generated by the standard Poseidon reference script and is used in
//! production by Light Protocol. We are NOT re-deriving or re-vetting those
//! parameters here -- if you need a different parameter set (different
//! width, different security margin) that's a separate, deliberate decision,
//! not something to improvise inline.
//!
//! Domain separation: leaf hashes and internal-node hashes must be
//! distinguishable, or an attacker can potentially pass off a valid internal
//! node as a fabricated leaf (a "second preimage" style tree-structure
//! attack). We tag leaves with a fixed nonzero domain constant as the first
//! input; internal nodes have no tag. This is a convention, not a proof --
//! confirm it matches whatever builds the tree off-chain (and the circuit,
//! if/when in-circuit verification lands per your acceptance criteria).

#![allow(dead_code)]

use ark_bn254::Fr;
use light_poseidon::{Poseidon, PoseidonBytesHasher};
use soroban_sdk::{BytesN, Env};

/// First input to every leaf hash: `Poseidon(LEAF_DOMAIN_TAG, preimage)`.
/// Internal nodes are `Poseidon(left, right)` with no tag, so a leaf hash
/// and a node hash live in distinguishable "shapes" by convention.
const LEAF_DOMAIN_TAG: [u8; 32] = {
    let mut tag = [0u8; 32];
    tag[31] = 1; // big-endian encoding of the field element `1`
    tag
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PoseidonHashError {
    /// `light-poseidon` rejected the input (bad arity, param init failure).
    HashFailed,
}

/// Poseidon(left, right) -- used for internal Merkle nodes.
pub fn hash_pair(
    env: &Env,
    left: &BytesN<32>,
    right: &BytesN<32>,
) -> Result<BytesN<32>, PoseidonHashError> {
    let mut hasher = Poseidon::<Fr>::new_circom(2).map_err(|_| PoseidonHashError::HashFailed)?;
    let out = hasher
        .hash_bytes_be(&[&left.to_array(), &right.to_array()])
        .map_err(|_| PoseidonHashError::HashFailed)?;
    Ok(BytesN::from_array(env, &out))
}

/// Poseidon(LEAF_DOMAIN_TAG, leaf_preimage) -- used for tree leaves.
/// `leaf_preimage` is whatever you commit per-eligible-address off-chain
/// (e.g. Poseidon(address, amount) computed at tree-build time) -- this
/// function does not construct that preimage, only hashes it into a leaf.
pub fn hash_leaf(env: &Env, leaf_preimage: &BytesN<32>) -> Result<BytesN<32>, PoseidonHashError> {
    let mut hasher = Poseidon::<Fr>::new_circom(2).map_err(|_| PoseidonHashError::HashFailed)?;
    let out = hasher
        .hash_bytes_be(&[&LEAF_DOMAIN_TAG, &leaf_preimage.to_array()])
        .map_err(|_| PoseidonHashError::HashFailed)?;
    Ok(BytesN::from_array(env, &out))
}
