// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | 'https://api.trivela.example.com' | (string & {});
};

export type Campaign = {
    /**
     * Campaign ID
     */
    id: string;
    /**
     * Campaign name
     */
    name: string;
    /**
     * URL-friendly slug
     */
    slug: string;
    /**
     * Campaign description
     */
    description: string;
    /**
     * Whether campaign is active
     */
    active: boolean;
    /**
     * Whether campaign is featured
     */
    featured: boolean;
    /**
     * Whether campaign is hidden
     */
    hidden?: boolean;
    /**
     * Reason for hiding campaign
     */
    hiddenReason?: string;
    /**
     * Reward points per action
     */
    rewardPerAction: number;
    /**
     * Campaign start date
     */
    startDate?: string;
    /**
     * Campaign end date
     */
    endDate?: string;
    /**
     * Campaign publish-workflow status
     */
    status: 'draft' | 'published' | 'archived';
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Public URL for campaign image
     */
    imageUrl?: string;
    /**
     * Campaign tags
     */
    tags?: Array<string>;
    /**
     * Campaign category
     */
    category?: string;
};

export type CampaignCreate = {
    /**
     * Campaign name
     */
    name: string;
    /**
     * URL-friendly slug (auto-generated if not provided)
     */
    slug?: string;
    /**
     * Campaign description
     */
    description?: string;
    /**
     * Reward points per action
     */
    rewardPerAction: number;
    /**
     * Whether campaign is active
     */
    active?: boolean;
    /**
     * Whether campaign is featured
     */
    featured?: boolean;
    /**
     * Whether campaign is hidden
     */
    hidden?: boolean;
    /**
     * Reason for hiding campaign
     */
    hiddenReason?: string;
    /**
     * Campaign start date
     */
    startDate?: string;
    /**
     * Campaign end date
     */
    endDate?: string;
    /**
     * Optional image URL
     */
    imageUrl?: string;
    tags?: Array<string>;
    /**
     * Category from controlled vocabulary
     */
    category?: string;
};

export type CampaignUpdate = {
    /**
     * Campaign name
     */
    name?: string;
    /**
     * URL-friendly slug
     */
    slug?: string;
    /**
     * Campaign description
     */
    description?: string;
    /**
     * Reward points per action
     */
    rewardPerAction?: number;
    /**
     * Whether campaign is active
     */
    active?: boolean;
    /**
     * Whether campaign is featured
     */
    featured?: boolean;
    /**
     * Whether campaign is hidden
     */
    hidden?: boolean;
    /**
     * Reason for hiding campaign
     */
    hiddenReason?: string;
    /**
     * Campaign start date
     */
    startDate?: string;
    /**
     * Campaign end date
     */
    endDate?: string;
};

export type CampaignListResponse = {
    data: Array<Campaign>;
    pagination: Pagination;
};

export type Pagination = {
    /**
     * Total number of items
     */
    total: number;
    /**
     * Number of items in current page
     */
    count: number;
    /**
     * Current page number
     */
    page: number;
    /**
     * Items per page
     */
    limit: number;
    /**
     * Number of items skipped
     */
    offset: number;
    /**
     * Total number of pages
     */
    totalPages: number;
    /**
     * Whether there is a previous page
     */
    hasPreviousPage: boolean;
    /**
     * Whether there is a next page
     */
    hasNextPage: boolean;
    /**
     * Previous page number
     */
    previousPage?: number;
    /**
     * Next page number
     */
    nextPage?: number;
};

export type HealthResponse = {
    /**
     * Overall health status
     */
    status: 'ok' | 'degraded';
    /**
     * Service name
     */
    service: string;
    /**
     * Health check timestamp
     */
    timestamp: string;
    rpc: RpcHealthResponse;
};

export type RpcHealthResponse = {
    /**
     * RPC health status
     */
    status: 'ok' | 'error';
    /**
     * RPC latency in milliseconds
     */
    latency_ms?: number;
    /**
     * Error message if status is error
     */
    error?: string;
};

export type ApiInfo = {
    name?: string;
    version?: string;
    prefix?: string;
    endpoints?: {
        [key: string]: unknown;
    };
    compatibility?: {
        [key: string]: unknown;
    };
    stellar?: {
        [key: string]: unknown;
    };
    config?: {
        [key: string]: unknown;
    };
    cors?: {
        [key: string]: unknown;
    };
    rateLimit?: {
        [key: string]: unknown;
    };
    body?: {
        [key: string]: unknown;
    };
};

export type ConfigResponse = {
    stellar: {
        network?: string;
        networkPassphrase?: string;
        sorobanRpcUrl?: string;
        horizonUrl?: string;
        explorerUrl?: string;
    };
    contracts: {
        rewards?: string;
        campaign?: string;
    };
};

export type ExplorerResponse = {
    network: string;
    explorerUrl: string;
};

export type AuditLogListResponse = {
    data: Array<AuditLog>;
    pagination: Pagination;
};

export type AuditLog = {
    id: string;
    actor: string;
    action: string;
    entity: string;
    entityId: string;
    diff?: {
        [key: string]: unknown;
    };
    timestamp: string;
};

export type IndexerCursorState = {
    cursor: string;
    updatedAt: string;
    source: string;
};

export type IndexerCursorUpdate = {
    cursor: string;
};

export type ApiKeyMetadata = {
    id?: string;
    label?: string;
    /**
     * Organization the key is scoped to, if any.
     */
    orgId?: string;
    /**
     * Granular permissions granted to the key.
     */
    scopes?: Array<ApiKeyScope>;
    rateTier?: ApiKeyRateTier;
    createdAt?: string;
    expiresAt?: string;
    lastUsedAt?: string;
    active?: boolean;
};

export type ApiKeyScope = 'campaigns:read' | 'campaigns:write' | 'allowlist:write' | 'admin';

/**
 * Per-key rate-limit tier enforced by the rate limiter (#924). `standard` is 60 req/min, `pro` is 300 req/min, `enterprise` is 1000 req/min.
 */
export type ApiKeyRateTier = 'standard' | 'pro' | 'enterprise';

export type PiiExportResponse = {
    success?: boolean;
    identifier?: string;
    exportedAt?: string;
    /**
     * One key per off-chain table with at least one matching row (empty tables are omitted). Values are arrays of the raw rows, except push_subscriptions.p256dh/auth which are redacted.
     */
    data?: {
        [key: string]: Array<{
            [key: string]: unknown;
        }>;
    };
};

export type PiiPurgeResponse = {
    success?: boolean;
    purged?: Array<{
        table?: string;
        count?: number;
    }>;
};

export type Error = {
    /**
     * Error message
     */
    error: string;
    /**
     * Error code
     */
    code: string;
};

export type ValidationError = {
    /**
     * Error message
     */
    error: string;
    /**
     * Error code
     */
    code: string;
    /**
     * Validation error details
     */
    details: Array<string>;
};

export type Organization = {
    /**
     * Organization ID
     */
    id: string;
    /**
     * Organization name
     */
    name: string;
    /**
     * URL-friendly slug
     */
    slug: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
};

export type OrganizationMember = {
    /**
     * Member ID
     */
    id: string;
    /**
     * Organization ID
     */
    organizationId: string;
    /**
     * Member email
     */
    userEmail: string;
    /**
     * Member role
     */
    role: 'owner' | 'admin' | 'member';
    /**
     * Join timestamp
     */
    joinedAt: string;
};

export type OrganizationInvitation = {
    /**
     * Invitation ID
     */
    id: string;
    /**
     * Organization ID
     */
    organizationId: string;
    /**
     * Invitee email
     */
    email: string;
    /**
     * Assigned role
     */
    role: 'owner' | 'admin' | 'member';
    /**
     * Secure invitation token
     */
    token: string;
    /**
     * Email of inviter
     */
    invitedBy: string;
    /**
     * Invitation timestamp
     */
    invitedAt: string;
    /**
     * Expiration timestamp
     */
    expiresAt: string;
    /**
     * Acceptance timestamp
     */
    acceptedAt?: string;
    /**
     * Revocation timestamp
     */
    revokedAt?: string;
    /**
     * Invitation status
     */
    status: 'pending' | 'accepted' | 'revoked' | 'expired';
};

export type CampaignStats = {
    /**
     * Campaign ID
     */
    campaignId: string;
    /**
     * Whether on-chain data has been synced
     */
    onChainSynced: boolean;
    range: {
        from?: string;
        to?: string;
    };
    summary: {
        /**
         * Total registered participants
         */
        totalParticipants: number;
        /**
         * Total points awarded
         */
        totalPoints: number;
        /**
         * Percentage of points claimed
         */
        claimRate: number;
        /**
         * Milliseconds until campaign ends
         */
        timeRemainingMs: number;
    };
    /**
     * Daily registration counts
     */
    registrationsByDay: Array<{
        date?: string;
        count?: number;
    }>;
    /**
     * Daily credited and claimed points
     */
    pointsByDay: Array<{
        date?: string;
        credited?: number;
        claimed?: number;
    }>;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Health status
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetRpcHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/rpc';
};

export type GetRpcHealthErrors = {
    /**
     * RPC is unavailable
     */
    503: RpcHealthResponse;
};

export type GetRpcHealthError = GetRpcHealthErrors[keyof GetRpcHealthErrors];

export type GetRpcHealthResponses = {
    /**
     * RPC is healthy
     */
    200: RpcHealthResponse;
};

export type GetRpcHealthResponse = GetRpcHealthResponses[keyof GetRpcHealthResponses];

export type GetMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metrics';
};

export type GetMetricsResponses = {
    /**
     * Prometheus-format metrics
     */
    200: string;
};

export type GetMetricsResponse = GetMetricsResponses[keyof GetMetricsResponses];

export type GetApiInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1';
};

export type GetApiInfoResponses = {
    /**
     * API metadata
     */
    200: ApiInfo;
};

export type GetApiInfoResponse = GetApiInfoResponses[keyof GetApiInfoResponses];

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config';
};

export type GetConfigResponses = {
    /**
     * Public configuration
     */
    200: ConfigResponse;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type GetExplorerLinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/explorer';
};

export type GetExplorerLinksResponses = {
    /**
     * Explorer configuration
     */
    200: ExplorerResponse;
};

export type GetExplorerLinksResponse = GetExplorerLinksResponses[keyof GetExplorerLinksResponses];

export type ListCampaignsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-indexed)
         */
        page?: number;
        /**
         * Items per page
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
        /**
         * Filter by active status
         */
        active?: true | false;
        /**
         * Full-text search query (supports phrases, prefix with *, boolean AND/OR/NOT)
         */
        q?: string;
        /**
         * Comma-separated tags (any match includes campaign)
         */
        tags?: string;
        /**
         * Filter by category
         */
        category?: string;
        /**
         * Sort field
         */
        sort?: string;
        /**
         * Sort order
         */
        order?: 'asc' | 'desc';
        /**
         * Filter by campaign status. Defaults to `published` for public (no API key) requests. Requesting `draft`, `archived`, or `all` requires an API key.
         */
        status?: 'draft' | 'published' | 'archived' | 'all';
    };
    url: '/api/v1/campaigns';
};

export type ListCampaignsErrors = {
    /**
     * API key required to access draft, archived, or all campaigns
     */
    401: Error;
};

export type ListCampaignsError = ListCampaignsErrors[keyof ListCampaignsErrors];

export type ListCampaignsResponses = {
    /**
     * Paginated campaign list
     */
    200: CampaignListResponse;
};

export type ListCampaignsResponse = ListCampaignsResponses[keyof ListCampaignsResponses];

export type CreateCampaignData = {
    body: CampaignCreate;
    path?: never;
    query?: never;
    url: '/api/v1/campaigns';
};

export type CreateCampaignErrors = {
    /**
     * Validation error
     */
    400: ValidationError;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Slug conflict
     */
    409: Error;
};

export type CreateCampaignError = CreateCampaignErrors[keyof CreateCampaignErrors];

export type CreateCampaignResponses = {
    /**
     * Campaign created
     */
    201: Campaign;
};

export type CreateCampaignResponse = CreateCampaignResponses[keyof CreateCampaignResponses];

export type DeleteCampaignData = {
    body?: never;
    path: {
        /**
         * Campaign ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/campaigns/{id}';
};

export type DeleteCampaignErrors = {
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Campaign not found
     */
    404: Error;
};

export type DeleteCampaignError = DeleteCampaignErrors[keyof DeleteCampaignErrors];

export type DeleteCampaignResponses = {
    /**
     * Campaign deleted
     */
    204: void;
};

export type DeleteCampaignResponse = DeleteCampaignResponses[keyof DeleteCampaignResponses];

export type GetCampaignByIdData = {
    body?: never;
    path: {
        /**
         * Campaign ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/campaigns/{id}';
};

export type GetCampaignByIdErrors = {
    /**
     * Campaign not found
     */
    404: Error;
};

export type GetCampaignByIdError = GetCampaignByIdErrors[keyof GetCampaignByIdErrors];

export type GetCampaignByIdResponses = {
    /**
     * Campaign details
     */
    200: Campaign;
};

export type GetCampaignByIdResponse = GetCampaignByIdResponses[keyof GetCampaignByIdResponses];

export type UpdateCampaignData = {
    body: CampaignUpdate;
    path: {
        /**
         * Campaign ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/campaigns/{id}';
};

export type UpdateCampaignErrors = {
    /**
     * Validation error
     */
    400: ValidationError;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Campaign not found
     */
    404: Error;
};

export type UpdateCampaignError = UpdateCampaignErrors[keyof UpdateCampaignErrors];

export type UpdateCampaignResponses = {
    /**
     * Campaign updated
     */
    200: Campaign;
};

export type UpdateCampaignResponse = UpdateCampaignResponses[keyof UpdateCampaignResponses];

export type GetCampaignStatsData = {
    body?: never;
    path: {
        /**
         * Campaign ID
         */
        id: string;
    };
    query?: {
        /**
         * Time range (7d, 30d, all)
         */
        range?: '7d' | '30d' | 'all';
        /**
         * Start date (ISO 8601)
         */
        from?: string;
        /**
         * End date (ISO 8601)
         */
        to?: string;
    };
    url: '/api/v1/campaigns/{id}/stats';
};

export type GetCampaignStatsErrors = {
    /**
     * Campaign not found
     */
    404: Error;
};

export type GetCampaignStatsError = GetCampaignStatsErrors[keyof GetCampaignStatsErrors];

export type GetCampaignStatsResponses = {
    /**
     * Campaign statistics
     */
    200: CampaignStats;
};

export type GetCampaignStatsResponse = GetCampaignStatsResponses[keyof GetCampaignStatsResponses];

export type GetCampaignBySlugData = {
    body?: never;
    path: {
        /**
         * Campaign slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/campaigns/by-slug/{slug}';
};

export type GetCampaignBySlugErrors = {
    /**
     * Campaign not found
     */
    404: Error;
};

export type GetCampaignBySlugError = GetCampaignBySlugErrors[keyof GetCampaignBySlugErrors];

export type GetCampaignBySlugResponses = {
    /**
     * Campaign details
     */
    200: Campaign;
};

export type GetCampaignBySlugResponse = GetCampaignBySlugResponses[keyof GetCampaignBySlugResponses];

export type UploadCampaignImageData = {
    body: {
        image: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/campaigns/{id}/image';
};

export type UploadCampaignImageErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Campaign not found
     */
    404: Error;
};

export type UploadCampaignImageError = UploadCampaignImageErrors[keyof UploadCampaignImageErrors];

export type UploadCampaignImageResponses = {
    /**
     * Image uploaded
     */
    200: {
        imageUrl?: string;
    };
};

export type UploadCampaignImageResponse = UploadCampaignImageResponses[keyof UploadCampaignImageResponses];

export type ListCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/categories';
};

export type ListCategoriesResponses = {
    /**
     * Category list
     */
    200: {
        data?: Array<{
            name?: string;
            count?: number;
        }>;
    };
};

export type ListCategoriesResponse = ListCategoriesResponses[keyof ListCategoriesResponses];

export type ListTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tags';
};

export type ListTagsResponses = {
    /**
     * Tag list
     */
    200: {
        data?: Array<{
            name?: string;
            count?: number;
        }>;
    };
};

export type ListTagsResponse = ListTagsResponses[keyof ListTagsResponses];

export type ListApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/api-keys';
};

export type ListApiKeysErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type ListApiKeysError = ListApiKeysErrors[keyof ListApiKeysErrors];

export type ListApiKeysResponses = {
    /**
     * API key list
     */
    200: {
        data?: Array<ApiKeyMetadata>;
    };
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
    body?: {
        label?: string;
        expiresAt?: string;
        /**
         * Scope the key to an organization.
         */
        orgId?: string;
        /**
         * Defaults to the full legacy scope set if omitted.
         */
        scopes?: Array<ApiKeyScope>;
        /**
         * Defaults to `standard` if omitted.
         */
        rateTier?: ApiKeyRateTier;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/api-keys';
};

export type CreateApiKeyResponses = {
    /**
     * API key created (raw key returned once)
     */
    201: {
        key?: string;
        metadata?: ApiKeyMetadata;
    };
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type RevokeApiKeyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/api-keys/{id}';
};

export type RevokeApiKeyErrors = {
    /**
     * Key not found
     */
    404: Error;
};

export type RevokeApiKeyError = RevokeApiKeyErrors[keyof RevokeApiKeyErrors];

export type RevokeApiKeyResponses = {
    /**
     * Key revoked
     */
    204: void;
};

export type RevokeApiKeyResponse = RevokeApiKeyResponses[keyof RevokeApiKeyResponses];

export type RotateApiKeyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/api-keys/{id}/rotate';
};

export type RotateApiKeyResponses = {
    /**
     * New key issued
     */
    200: {
        key?: string;
        metadata?: ApiKeyMetadata;
    };
};

export type RotateApiKeyResponse = RotateApiKeyResponses[keyof RotateApiKeyResponses];

export type UpdateApiKeyRateTierData = {
    body: {
        rateTier: ApiKeyRateTier;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/api-keys/{id}/rate-tier';
};

export type UpdateApiKeyRateTierErrors = {
    /**
     * Invalid rate tier value
     */
    400: ValidationError;
    /**
     * Key not found
     */
    404: Error;
};

export type UpdateApiKeyRateTierError = UpdateApiKeyRateTierErrors[keyof UpdateApiKeyRateTierErrors];

export type UpdateApiKeyRateTierResponses = {
    /**
     * Rate tier updated
     */
    200: {
        metadata?: ApiKeyMetadata;
    };
};

export type UpdateApiKeyRateTierResponse = UpdateApiKeyRateTierResponses[keyof UpdateApiKeyRateTierResponses];

export type ExportPiiForUserData = {
    body: {
        /**
         * Wallet address (G...) or email to export data for.
         */
        identifier: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/pii/export-user';
};

export type ExportPiiForUserErrors = {
    /**
     * Missing identifier
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type ExportPiiForUserError = ExportPiiForUserErrors[keyof ExportPiiForUserErrors];

export type ExportPiiForUserResponses = {
    /**
     * Export payload
     */
    200: PiiExportResponse;
};

export type ExportPiiForUserResponse = ExportPiiForUserResponses[keyof ExportPiiForUserResponses];

export type PurgePiiForUserData = {
    body: {
        /**
         * Wallet address (G...) or email to purge data for.
         */
        identifier: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/pii/purge-user';
};

export type PurgePiiForUserErrors = {
    /**
     * Missing identifier
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type PurgePiiForUserError = PurgePiiForUserErrors[keyof PurgePiiForUserErrors];

export type PurgePiiForUserResponses = {
    /**
     * Purge result
     */
    200: PiiPurgeResponse;
};

export type PurgePiiForUserResponse = PurgePiiForUserResponses[keyof PurgePiiForUserResponses];

export type PurgePiiForCampaignData = {
    body: {
        campaignId: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/pii/purge-campaign';
};

export type PurgePiiForCampaignErrors = {
    /**
     * Missing campaignId
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type PurgePiiForCampaignError = PurgePiiForCampaignErrors[keyof PurgePiiForCampaignErrors];

export type PurgePiiForCampaignResponses = {
    /**
     * Purge result
     */
    200: PiiPurgeResponse;
};

export type PurgePiiForCampaignResponse = PurgePiiForCampaignResponses[keyof PurgePiiForCampaignResponses];

export type ListAuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by entity type
         */
        entity?: string;
        /**
         * Filter by entity ID
         */
        entityId?: string;
        /**
         * Filter by action
         */
        action?: 'create' | 'update' | 'delete';
        page?: number;
        limit?: number;
    };
    url: '/api/v1/audit-logs';
};

export type ListAuditLogsErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type ListAuditLogsError = ListAuditLogsErrors[keyof ListAuditLogsErrors];

export type ListAuditLogsResponses = {
    /**
     * Paginated audit log list
     */
    200: AuditLogListResponse;
};

export type ListAuditLogsResponse = ListAuditLogsResponses[keyof ListAuditLogsResponses];

export type GetIndexerCursorData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/indexer/cursor';
};

export type GetIndexerCursorResponses = {
    /**
     * Cursor state
     */
    200: IndexerCursorState;
};

export type GetIndexerCursorResponse = GetIndexerCursorResponses[keyof GetIndexerCursorResponses];

export type SetIndexerCursorData = {
    body: IndexerCursorUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/indexer/cursor';
};

export type SetIndexerCursorErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type SetIndexerCursorError = SetIndexerCursorErrors[keyof SetIndexerCursorErrors];

export type SetIndexerCursorResponses = {
    /**
     * Cursor updated
     */
    200: IndexerCursorState;
};

export type SetIndexerCursorResponse = SetIndexerCursorResponses[keyof SetIndexerCursorResponses];

export type CreateOrganizationData = {
    body: {
        name: string;
        slug?: string;
        creatorEmail?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/organizations';
};

export type CreateOrganizationErrors = {
    /**
     * Validation error
     */
    400: ValidationError;
    /**
     * Unauthorized
     */
    401: Error;
};

export type CreateOrganizationError = CreateOrganizationErrors[keyof CreateOrganizationErrors];

export type CreateOrganizationResponses = {
    /**
     * Organization created
     */
    201: Organization;
};

export type CreateOrganizationResponse = CreateOrganizationResponses[keyof CreateOrganizationResponses];

export type DeleteOrganizationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}';
};

export type DeleteOrganizationErrors = {
    /**
     * Organization not found
     */
    404: Error;
};

export type DeleteOrganizationError = DeleteOrganizationErrors[keyof DeleteOrganizationErrors];

export type DeleteOrganizationResponses = {
    /**
     * Organization deleted
     */
    204: void;
};

export type DeleteOrganizationResponse = DeleteOrganizationResponses[keyof DeleteOrganizationResponses];

export type GetOrganizationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}';
};

export type GetOrganizationErrors = {
    /**
     * Organization not found
     */
    404: Error;
};

export type GetOrganizationError = GetOrganizationErrors[keyof GetOrganizationErrors];

export type GetOrganizationResponses = {
    /**
     * Organization details
     */
    200: Organization;
};

export type GetOrganizationResponse = GetOrganizationResponses[keyof GetOrganizationResponses];

export type UpdateOrganizationData = {
    body?: {
        name?: string;
        slug?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}';
};

export type UpdateOrganizationErrors = {
    /**
     * Organization not found
     */
    404: Error;
};

export type UpdateOrganizationError = UpdateOrganizationErrors[keyof UpdateOrganizationErrors];

export type UpdateOrganizationResponses = {
    /**
     * Organization updated
     */
    200: Organization;
};

export type UpdateOrganizationResponse = UpdateOrganizationResponses[keyof UpdateOrganizationResponses];

export type ListMembersData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/members';
};

export type ListMembersResponses = {
    /**
     * List of members
     */
    200: {
        data?: Array<OrganizationMember>;
    };
};

export type ListMembersResponse = ListMembersResponses[keyof ListMembersResponses];

export type RemoveMemberData = {
    body?: never;
    path: {
        id: string;
        memberId: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/members/{memberId}';
};

export type RemoveMemberErrors = {
    /**
     * Invalid operation (e.g., removing last owner)
     */
    400: Error;
    /**
     * Member not found
     */
    404: Error;
};

export type RemoveMemberError = RemoveMemberErrors[keyof RemoveMemberErrors];

export type RemoveMemberResponses = {
    /**
     * Member removed
     */
    204: void;
};

export type RemoveMemberResponse = RemoveMemberResponses[keyof RemoveMemberResponses];

export type UpdateMemberRoleData = {
    body: {
        role: 'owner' | 'admin' | 'member';
    };
    path: {
        id: string;
        memberId: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/members/{memberId}';
};

export type UpdateMemberRoleErrors = {
    /**
     * Validation error or invalid operation
     */
    400: Error;
    /**
     * Member not found
     */
    404: Error;
};

export type UpdateMemberRoleError = UpdateMemberRoleErrors[keyof UpdateMemberRoleErrors];

export type UpdateMemberRoleResponses = {
    /**
     * Member role updated
     */
    200: OrganizationMember;
};

export type UpdateMemberRoleResponse = UpdateMemberRoleResponses[keyof UpdateMemberRoleResponses];

export type ListInvitationsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        status?: 'pending' | 'accepted' | 'revoked' | 'expired';
    };
    url: '/api/v1/organizations/{id}/invitations';
};

export type ListInvitationsResponses = {
    /**
     * List of invitations
     */
    200: {
        data?: Array<OrganizationInvitation>;
    };
};

export type ListInvitationsResponse = ListInvitationsResponses[keyof ListInvitationsResponses];

export type CreateInvitationData = {
    body: {
        email: string;
        role: 'owner' | 'admin' | 'member';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/invitations';
};

export type CreateInvitationErrors = {
    /**
     * Validation error
     */
    400: ValidationError;
    /**
     * Organization not found
     */
    404: Error;
};

export type CreateInvitationError = CreateInvitationErrors[keyof CreateInvitationErrors];

export type CreateInvitationResponses = {
    /**
     * Invitation created
     */
    201: {
        type?: 'invitation_created' | 'invitation_exists' | 'already_member' | 'member_updated';
        invitation?: OrganizationInvitation;
        inviteLink?: string;
        member?: OrganizationMember;
    };
};

export type CreateInvitationResponse = CreateInvitationResponses[keyof CreateInvitationResponses];

export type RevokeInvitationData = {
    body?: never;
    path: {
        id: string;
        invitationId: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/invitations/{invitationId}';
};

export type RevokeInvitationErrors = {
    /**
     * Invalid operation
     */
    400: Error;
    /**
     * Invitation not found
     */
    404: Error;
};

export type RevokeInvitationError = RevokeInvitationErrors[keyof RevokeInvitationErrors];

export type RevokeInvitationResponses = {
    /**
     * Invitation revoked
     */
    200: {
        type?: string;
        invitation?: OrganizationInvitation;
    };
};

export type RevokeInvitationResponse = RevokeInvitationResponses[keyof RevokeInvitationResponses];

export type GetInvitationByTokenData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/api/v1/organizations/invite/{token}';
};

export type GetInvitationByTokenErrors = {
    /**
     * Invitation not found
     */
    404: Error;
};

export type GetInvitationByTokenError = GetInvitationByTokenErrors[keyof GetInvitationByTokenErrors];

export type GetInvitationByTokenResponses = {
    /**
     * Invitation details
     */
    200: {
        email?: string;
        role?: string;
        organization?: {
            id?: string;
            name?: string;
        };
        status?: string;
        expiresAt?: string;
    };
};

export type GetInvitationByTokenResponse = GetInvitationByTokenResponses[keyof GetInvitationByTokenResponses];

export type AcceptInvitationData = {
    body: {
        email: string;
    };
    path: {
        token: string;
    };
    query?: never;
    url: '/api/v1/organizations/invite/{token}/accept';
};

export type AcceptInvitationErrors = {
    /**
     * Invalid invitation or validation error
     */
    400: Error;
};

export type AcceptInvitationError = AcceptInvitationErrors[keyof AcceptInvitationErrors];

export type AcceptInvitationResponses = {
    /**
     * Invitation accepted
     */
    200: {
        type?: string;
        member?: OrganizationMember;
        organization?: Organization;
    };
};

export type AcceptInvitationResponse = AcceptInvitationResponses[keyof AcceptInvitationResponses];

export type GetWellKnownStellarTomlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/.well-known/stellar.toml';
};

export type GetWellKnownStellarTomlResponses = {
    /**
     * Valid SEP-1 TOML document
     */
    200: string;
};

export type GetWellKnownStellarTomlResponse = GetWellKnownStellarTomlResponses[keyof GetWellKnownStellarTomlResponses];

export type GetApiV1IndexCampaignsByIdParticipantsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        /**
         * Opaque pagination cursor from previous response
         */
        cursor?: string;
        limit?: number;
    };
    url: '/api/v1/index/campaigns/{id}/participants';
};

export type GetApiV1IndexCampaignsByIdParticipantsErrors = {
    /**
     * Campaign not found
     */
    404: unknown;
};

export type GetApiV1IndexCampaignsByIdParticipantsResponses = {
    /**
     * Paginated participant list with freshness indicator
     */
    200: {
        data?: Array<{
            address?: string;
            balance?: string;
        }>;
        cursor?: string;
        has_more?: boolean;
        as_of_ledger?: number;
    };
};

export type GetApiV1IndexCampaignsByIdParticipantsResponse = GetApiV1IndexCampaignsByIdParticipantsResponses[keyof GetApiV1IndexCampaignsByIdParticipantsResponses];

export type GetApiV1IndexCampaignsByIdEventsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        /**
         * Filter by event type
         */
        type?: 'credit' | 'claim';
        cursor?: string;
        limit?: number;
    };
    url: '/api/v1/index/campaigns/{id}/events';
};

export type GetApiV1IndexCampaignsByIdEventsErrors = {
    /**
     * Campaign not found
     */
    404: unknown;
};

export type GetApiV1IndexCampaignsByIdEventsResponses = {
    /**
     * Paginated event list
     */
    200: {
        data?: Array<{
            user?: string;
            amount?: string;
            ledger?: number;
            tx_hash?: string;
            type?: 'credit' | 'claim';
        }>;
        cursor?: string;
        has_more?: boolean;
        as_of_ledger?: number;
    };
};

export type GetApiV1IndexCampaignsByIdEventsResponse = GetApiV1IndexCampaignsByIdEventsResponses[keyof GetApiV1IndexCampaignsByIdEventsResponses];

export type GetApiV1IndexAddressesByAddressHistoryData = {
    body?: never;
    path: {
        address: string;
    };
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/v1/index/addresses/{address}/history';
};

export type GetApiV1IndexAddressesByAddressHistoryResponses = {
    /**
     * Address event history and current balance
     */
    200: {
        address?: string;
        balance?: string;
        data?: Array<unknown>;
        cursor?: string;
        has_more?: boolean;
        as_of_ledger?: number;
    };
};

export type GetApiV1IndexAddressesByAddressHistoryResponse = GetApiV1IndexAddressesByAddressHistoryResponses[keyof GetApiV1IndexAddressesByAddressHistoryResponses];

export type GetApiV1IndexCampaignsByIdStatsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/index/campaigns/{id}/stats';
};

export type GetApiV1IndexCampaignsByIdStatsErrors = {
    /**
     * Campaign not found
     */
    404: unknown;
};

export type GetApiV1IndexCampaignsByIdStatsResponses = {
    /**
     * Campaign stats
     */
    200: {
        campaignId?: string;
        as_of_ledger?: number;
        summary?: {
            totalParticipants?: number;
            totalCredited?: string;
            totalClaimed?: string;
            claimRate?: number;
        };
    };
};

export type GetApiV1IndexCampaignsByIdStatsResponse = GetApiV1IndexCampaignsByIdStatsResponses[keyof GetApiV1IndexCampaignsByIdStatsResponses];

export type PostApiV1SponsoredAccountsData = {
    body: {
        /**
         * Stellar G-address to sponsor
         */
        address: string;
        accountType?: 'stellar' | 'smart_wallet';
        /**
         * "CODE:ISSUER" trustline to add within the sponsorship envelope
         */
        trustlineAsset?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/sponsored-accounts';
};

export type PostApiV1SponsoredAccountsErrors = {
    /**
     * Invalid address or asset format
     */
    400: unknown;
    /**
     * Address already has an active sponsorship
     */
    409: unknown;
};

export type PostApiV1SponsoredAccountsResponses = {
    /**
     * Sponsorship created; returns partially-signed transaction XDR
     */
    201: unknown;
    /**
     * Sponsorship tracked (SPONSOR_SECRET_KEY not configured)
     */
    202: unknown;
};

export type GetApiV1SponsoredAccountsByAddressData = {
    body?: never;
    path: {
        address: string;
    };
    query?: never;
    url: '/api/v1/sponsored-accounts/{address}';
};

export type GetApiV1SponsoredAccountsByAddressErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type GetApiV1SponsoredAccountsByAddressResponses = {
    /**
     * Sponsorship record
     */
    200: unknown;
};

export type PostApiV1SponsoredAccountsByAddressRevokeData = {
    body?: never;
    path: {
        address: string;
    };
    query?: never;
    url: '/api/v1/sponsored-accounts/{address}/revoke';
};

export type PostApiV1SponsoredAccountsByAddressRevokeErrors = {
    /**
     * No active sponsorship for this address
     */
    404: unknown;
};

export type PostApiV1SponsoredAccountsByAddressRevokeResponses = {
    /**
     * Revocation XDR built; or tracked-only if key not configured
     */
    200: unknown;
};

export type GetApiV1CampaignsByIdClaimableBalancesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        status?: 'pending' | 'created' | 'claimed_by_user' | 'reclaimed_by_operator' | 'failed';
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/campaigns/{id}/claimable-balances';
};

export type GetApiV1CampaignsByIdClaimableBalancesResponses = {
    /**
     * Paginated claimable balance list
     */
    200: unknown;
};

export type PostApiV1CampaignsByIdClaimableBalancesData = {
    body?: {
        graceDays?: number;
        assetCode?: string;
        assetIssuer?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/campaigns/{id}/claimable-balances';
};

export type PostApiV1CampaignsByIdClaimableBalancesErrors = {
    /**
     * Campaign not found
     */
    404: unknown;
};

export type PostApiV1CampaignsByIdClaimableBalancesResponses = {
    /**
     * Submission enqueued on the durable job queue; returns { ok, campaignId, jobId, status: "queued" } immediately. Poll GET on this same path to see rows move pending -> created/failed.
     */
    202: unknown;
};

export type PostApiV1CampaignsByIdClaimableBalancesReclaimData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/campaigns/{id}/claimable-balances/reclaim';
};

export type PostApiV1CampaignsByIdClaimableBalancesReclaimErrors = {
    /**
     * Campaign not found
     */
    404: unknown;
};

export type PostApiV1CampaignsByIdClaimableBalancesReclaimResponses = {
    /**
     * Balances marked as reclaimed
     */
    200: unknown;
};
